//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace PrairieCMS.Core
{
    public partial class cmsContent_Type_Mapping
    {
        public int pkBcId { get; set; }
        public int fkParent { get; set; }
        public int fkEditorsRole { get; set; }
        public int fkContentType { get; set; }
        public Nullable<int> fkContent { get; set; }
        public string insertionPoint { get; set; }
        public System.DateTime dateCreated { get; set; }
        public string createdBy { get; set; }
        public System.DateTime dateModified { get; set; }
        public string modifiedBy { get; set; }
    
        public virtual cmsContent_Type cmsContent_Type { get; set; }
        public virtual Content_Template Content_Template { get; set; }
        public virtual webpages_Roles webpages_Roles { get; set; }
        public virtual cms_Page_Map cms_Page_Map { get; set; }
    }
    
}
