//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

namespace PrairieCMS.Core
{
    public partial class cmsEntities : DbContext
    {
        public cmsEntities()
            : base("name=cmsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<cmsContent_Type> cmsContent_Type { get; set; }
        public DbSet<cmsContent_Type_Mapping> cmsContent_Type_Mapping { get; set; }
        public DbSet<cmsLevel_Mapping> cmsLevel_Mapping { get; set; }
        public DbSet<cmsSiteSetup> cmsSiteSetups { get; set; }
        public DbSet<Content_Template> Content_Template { get; set; }
        public DbSet<Log> Logs { get; set; }
        public DbSet<Master_Template> Master_Template { get; set; }
        public DbSet<User> Users { get; set; }
        public DbSet<webpages_Membership> webpages_Membership { get; set; }
        public DbSet<webpages_OAuthMembership> webpages_OAuthMembership { get; set; }
        public DbSet<webpages_Roles> webpages_Roles { get; set; }
        public DbSet<cms_Page_Map> cms_Page_Map { get; set; }
    }
}
