//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace PrairieCMS.Core
{
    public partial class cmsLevel_Mapping
    {
        public cmsLevel_Mapping()
        {
            this.cmsContent_Type = new HashSet<cmsContent_Type>();
        }
    
        public int pkLevelMappingId { get; set; }
        public string pageLevelDescriptor { get; set; }
    
        public virtual ICollection<cmsContent_Type> cmsContent_Type { get; set; }
    }
    
}
