//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace PrairieCMS.Core
{
    public partial class cmsSiteSetup
    {
        public int pkSiteSetupId { get; set; }
        public int fkMaster_Template { get; set; }
        public int fkFooterContentId { get; set; }
        public System.DateTime dateCreated { get; set; }
        public string createdBy { get; set; }
        public System.DateTime dateModified { get; set; }
        public string modifiedBy { get; set; }
    
        public virtual Master_Template Master_Template { get; set; }
        public virtual Master_Template Master_Template1 { get; set; }
    }
    
}
