//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace PrairieCMS.Core
{
    public partial class Content_Template
    {
        public Content_Template()
        {
            this.cmsContent_Type_Mapping = new HashSet<cmsContent_Type_Mapping>();
        }
    
        public int pkContentID { get; set; }
        public string contentName { get; set; }
        public string html { get; set; }
        public int belongsTo { get; set; }
        public System.DateTime createdOn { get; set; }
        public string createdBy { get; set; }
        public System.DateTime modifiedOn { get; set; }
        public string modifiedBy { get; set; }
        public string markDown { get; set; }
    
        public virtual ICollection<cmsContent_Type_Mapping> cmsContent_Type_Mapping { get; set; }
    }
    
}
