//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace PrairieCMS.Core
{
    public partial class Log
    {
        public int pkId { get; set; }
        public string Category { get; set; }
        public string Info { get; set; }
        public Nullable<System.DateTime> Date_Entered { get; set; }
    }
    
}
